name: cs229_project
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.4=py310h9128911_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2022.5.18.1=py310haa95532_0
  - cffi=1.15.0=py310h2bbff1b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310haa95532_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py310h21b164f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - future=0.18.2=py310haa95532_1
  - huggingface_hub=0.2.1=pyhd3eb1b0_0
  - icu=58.2=ha925a31_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py310haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - kiwisolver=1.4.2=py310hd77b12b_0
  - libffi=3.4.2=h604cdb4_1
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=he0120a3_1
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.2=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - matplotlib=3.5.1=py310haa95532_1
  - matplotlib-base=3.5.1=py310hd77b12b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - munkres=1.1.4=py_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - numexpr=2.8.1=py310hb57aa6b_1
  - numpy=1.22.3=py310h6d2d95c_0
  - numpy-base=1.22.3=py310h206c741_0
  - openssl=1.1.1o=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.2=py310hd77b12b_0
  - pillow=9.0.1=py310hdc2b20a_0
  - pip=21.2.4=py310haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py310hd77b12b_6
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.4=hbb2ffb3_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.2=cpu_py310habb1308_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py310h2bbff1b_0
  - qt=5.9.7=vc14h73c81de_0
  - regex=2022.3.15=py310h2bbff1b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - setuptools=61.2.0=py310haa95532_0
  - sip=4.19.13=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=h2bbff1b_0
  - tk=8.6.11=h2bbff1b_1
  - tokenizers=0.11.4=py310he5181cf_1
  - tornado=6.1=py310h2bbff1b_0
  - tqdm=4.64.0=py310haa95532_0
  - transformers=4.18.0=py310haa95532_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.5=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zipp=3.8.0=py310haa95532_0
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0